### ISSUE TITLE
Improve Opencast overview page UX by replacing icons with Bootstrap badges

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#199]
Currently, the Opencast overview page uses icons to inform the teacher about the processing status and visibility status of the videos. The icons have tooltips, but they still are cryptical to some teachers at first:

![grafik](https://user-images.githubusercontent.com/1092118/117625412-495cae00-b176-11eb-8230-ac5b9b1814a4.png)

I would propose to re-think this approach and use Bootstrap badges (https://getbootstrap.com/docs/4.0/components/badge/) instead of icons. Teachers are especially used to see badges on the course overview pages for visibility information and we would be able to ship some more and clear information to teacher by using short texts within the badges.

Here's a quick mockup how this could look like:
![grafik](https://user-images.githubusercontent.com/1092118/117627730-bf621480-b178-11eb-888a-0c8a7311eefe.png)

**Comment by TamaraGunkel** [comment]
Actually, I like the icons. They are small and easily distinguishable. When using badges you have to read the text because the colors might not direclty indicate the status (e.g. we would have to use yellow for "Needs cutting" and "Processing in progress"). The same applies to the difference in the status and the visibility where we have currently different icons. Additionally, I'm afraid that the badges take up too much space when using more columns:

![grafik](https://user-images.githubusercontent.com/28386141/118974976-be4c9680-b973-11eb-9d3d-c3ef5f1ea1d3.png)

But I can understand that they might be not directly understood by teachers. Maybe we could use boostrap tooltips that are more obvious or add a legend below the table?

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
Could you please assign this issue to me?
Thanks in advance
