### ISSUE TITLE
Feature request: Allow students to download videos

### ISSUE THREAD

**Issue by TamaraGunkel** [Opencast-Moodle/moodle-block_opencast#201]
From #97:
We have received a feature request that allows students to download the videos to watch them offline. The call for this feature request became louder during the COV lockdown period. 

I guess it is still not possible to implement this feature with the current Opencast Moodle plugins, right?

I recommend to generally think about a configurable download option. One idea would be that admins can enable/disable the download function within the block with the following options:

1. only for `editingteacher` => teachers in a Moodle course
2. only for `editingteacher`  and `noneditingteachers` => teachers and tutors in a Moodle course
3. for all course participants (including `students`)
Preferably, a way may be found for teachers to configure themselves whether the download option should be enabled for students.

Download for teachers is already available, download for students not yet.
However, I would see the download option for students rather in the mod_opencast activity than in the block.

**Comment by abias** [comment]
Just as a side note:
We have configured Opencast to allow students to download videos within the Paella player as well as within the Opencast LTI series list. 

Paella player:
![grafik](https://user-images.githubusercontent.com/1092118/122519413-bafc0780-d012-11eb-8cc5-811d73166432.png)

Opencast LTI series list:
![grafik](https://user-images.githubusercontent.com/1092118/122519618-f1398700-d012-11eb-8944-818d5068ada8.png)

Having this functionality at the place where videos are viewed, students have never raised the need to download the videos directly from within the Moodle plugin.

**Comment by tjettmers** [comment]
We had activated this function within the paella. But not all teachers were happy, that students could download their videos. So we had to retract this and would be very happy if teachers could configurate this for each course and/or series or even  episode.

**Comment by abias** [comment]
Point taken. However, I don't agree that this should be a teacher's decision.

Teachers tend not to allow video downloads while students tend to demand them for mobile usage (without network connection) and for personal study / archive purposes. We have seen this over years in our lecture capture service.

When boosting our systems for the covid pandemic measures in early 2020, we switch to a simply policy that video downloads within our Opencast system are mandatory so that students can download the videos and use them anytime anywhere. We had some rants and complaints from teachers, but in the end the policy was accepted and students are simply benefitting from the download offer since then.

Besides this political decision, I see the major problem in this issue here that there is simply no real UI which students are using as block_opencast is primarily designed to upload and manage videos, not view then. Students do not see the Opencast overview page. Students even might not see the block itself in the course (see https://moodle.docs.opencast.org/#block/about.html#placement). And if they see the block, the real estate is really limited.

From my point of view, this decision could be moved to mod_opencast and discussed there - at the place where students are viewing the videos.

Cheers,
Alex

**Comment by TamaraGunkel** [comment]
Hey, 
its great to see that you have enabled that for all students just by configuring the Paella player. 
Could you share the config file?

I guess the best possibility is to allow global downloads by configuring the config file (and adding that to the documentation). An additional feature (with the possibility to disable it) should allow teachers to decide on the download functionality per series, maybe even video. Not all universities will be happy with a global download, also because of data protection.

And as I already wrote in the description, I do agree with you that this rather affects the mod plugin. There is already an issue: https://github.com/Opencast-Moodle/moodle-mod_opencast/issues/5
So I'll close this and we can move the discussion to the activity.

**Comment by abias** [comment]
> its great to see that you have enabled that for all students just by configuring the Paella player.
> Could you share the config file?

The configuration in Opencast was done by my colleague. I will ask her to post the details here.

**Comment by wsmirnow** [comment]
Hi,
the Paella screenshot above shows the Paella downlaod plugin. It is disabled by default. You can change it be setting the `enabled` flag to `true` in the [Paella configuration](https://github.com/opencast/opencast/blob/r/10.x/etc/ui-config/mh_default_org/paella/config.json#L381-L386). This configuration is global and will apply to all videos you deliver with Opencast.

The LTI option may be enabled globally or per course by setting the property `download`=`true`, see [Opencast Documentation](https://docs.opencast.org/r/10.x/admin/#modules/ltimodule.html#specifying-lti-tools).

**Comment by jqr86** [comment]
Hi,
die LTI Tool Anpassung ist seit Opencast 9.5 und Paealla Plugin seit 9.4 in der Communityversion verfügbar.

**Comment by TamaraGunkel** [comment]
Great, thank you @wsmirnow !
I'll add this to the documentation so that others can enable the download globally if they want.
