### ISSUE TITLE
Processing fails for long file names

### ISSUE THREAD

**Issue by Rillke** [Opencast-Moodle/moodle-block_opencast#204]
1. Install the block and navigate to a block in your course
2. Add a file from disk whose name is >>128 characters, for instance `verrry long file name ipsum quia dolor sit amet the red brown fox jumps over the whatever just make it loooooong very very very long ilias_cant_join ksjskfjswke lkwe34k3jfskdf kwflwsrerjer.mp4`
3. Upload
4. Image job fails during processing.

Either the user should be prompted to shorten the file name, the plugin should reject submitting videos with too long file names, or the plugin should truncate the file names or Opencast should deal with that https://github.com/opencast/opencast/issues/2699

**Comment by TamaraGunkel** [comment]
Hi,
thanks for reporting this. 
However, as you're already reviewing the [pull request](https://github.com/opencast/opencast/pull/2723) fixing that in Opencast, I'd not implement an additional solution in the block. That makes it easier for us because we don't have to try staying consistent with the Opencast restrictions.
Thus I'll close the issue. If you think that additional work should be done in the plugin, I'll reopen the issue.
