### ISSUE TITLE
'isdefault' in mdl_tool_opencast_series should be unique for a moodle course

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#232]
Hello,

we had an error in the OC series management of a Moodle course these days. When editing the settings of a series, the loading time for that page was extremely slow. So a colleague of mine started editing the series settings and he saved the editing several times. In addition to the actual series, three other series have been created in the background, although this wasn't intended. These three additional series could not be deleted from the Moodle page it self, because all four series of the Moodle course were marked as default series in the database table mdl_tool_opencast_series (isdefault=1). Only the deletion of the series in the database and in OC led to success. Would it not be acceptable to define that there may only be one default series for a Moodle course? Like a constrain?

Thanks & Greetings,
Michael

**Comment by TamaraGunkel** [comment]
Hey,
I'm still not convinced that the advantages of locking outweigh the disadvantages. But we can talk about this tomorrow if you're there.

OC GUI? Why should that interfere with the API?

**Comment by bluetom** [comment]
I definitely think there should only one course series be "default".

**Comment by ferishili** [comment]
To have a unique combination of `series` and `isdefault` in that table, we have 2 options:
1. DB `TRIGGERS`: That makes sure on update or new insert that there is only 1 record containing a series id that has `isdeafult = 1`
2. Application level: Take care of this scenario very thoroughly in application level. Like add checkers [there are currently some] to update and insert of series into a course.

We are force to take the second option, because it is not possible to deliver the db trigger (as changes) in a common way in the code, therefore it is not possible to solve it at db level (it is more than a simple index record it table)
