### ISSUE TITLE
Opencast Studio not processing video

### ISSUE THREAD

**Issue by emmarichardson** [Opencast-Moodle/moodle-block_opencast#243]
If I start a new recording from Moodle course, the studio allows the recording to happen but then loads a blank page.  
Everything else seems to be working except the recording process. I can upload existing videos from the block and they are processed correctly. If I click on the record video button from the block, it takes me to studio and I can start to make a recording - but once I have finished and I click on the stop recording icon, it loads a blank page and nothing happens.  Looking at the console in chrome developer tools, shows me this:

react-dom.production.min.js:216 RangeError: Incorrect locale information provided
    at Number.toLocaleString (<anonymous>)
    at e.format (index.js:51)
    at f (i18next.js:1387)
    at i18next.js:1410
    at Array.forEach (<anonymous>)
    at e.value (i18next.js:1406)
    at t.value (i18next.js:749)
    at t.value (i18next.js:719)
    at t.value (i18next.js:2213)
    at e (i18next.js:2196)

I noticed that &lang=en_us is being added to the url and am wondering if that is what is causing the issue.   Wondering if I missed something in the settings...

**Comment by TamaraGunkel** [comment]
Hey,
that seems as if Opencast Studio isn't able to process the language correctly. In my opinion, `en_us` is a valid locale code that OC studio should be able to process. However, I don't have any idea about the implementation of OC studio and if there are some restrictions regarding the language codes. 

I think it would be best if you're asking the developers of OC studio because I don't think it's an issue with the plugin. If they're saying that only specific language codes are supported, we can adapt the plugin but it would be best if OC studio supports the standard locale codes.
