### ISSUE TITLE
Mass action support for resource entries of courses

### ISSUE THREAD

**Issue by colradectug** [Opencast-Moodle/moodle-block_opencast#245]
Opencast allows to set the visibility of each Video by clicking on the "eye" icon. However, it is not possible to select multiple videos at once.

![image](https://user-images.githubusercontent.com/95869793/149133480-4f9dd693-c2c3-4e4f-8d52-fd84518f6a82.png)

One could consider checkboxes with the action to be chosen from a drop-down menu at the bottom of the table (to be done with mass-actions) in addition to the existing columns.

**Comment by wiebkemueller-hsh** [comment]
Hello @ferishili, is there any chance this will be implemented in the near future? Can we do anything to give this priority? We're being asked this frequently by our teachers. Regards! Wiebke

**Comment by ferishili** [comment]
Hi @wiebkemueller-hsh,
I have tried to email you the information, did you receive it?

**Comment by ferishili** [comment]
The Mass-actions that are going to be provided are as follows:
- Delete
- Update metadata
- Change Visibility
- Start workflow

**Comment by wiebkemueller-hsh** [comment]
Hi Farbod, what's behind "start workflow"? Is this an option that teachers would be able to handle? If yes maybe it would be a good idea to give this a more specific title? Thx Wiebke

**Comment by ferishili** [comment]
Hi @wiebkemueller-hsh,
"Start workflow" is a feature/option by which the teachers could start a workflow on a single video (of course which admin configures in the settings via `workflow_tags` option)
Generally, Workflows in opencast are a set of processes that could be defined and then opencast will perform on a video!
It depends on the opencast sys-admin decision what to offer and what not!

The title here is exactly the title that has been used before in the single video actions menu, so I would not recommend to suddenly change it in here (mass-action), because that would create confusion for those who are familiar with this option!
