### ISSUE TITLE
Faulty series definition in Opencast

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-block_opencast#259]
Faulty series definition in Opencast (event details show no series), when more than one series ID is set in the Moodle Opencast block. The series name are shown in the listing of the videos in Opencast (for the corresponding uploaded event). But if you click on the events series name (in the Opencast video overview), to get the series content listed, you get an empty search result - The series search has no name.

It seems that the series are not registered in Opencast when uploading the event via the Moodle Opencast block. 

Also important to note: If you go into the event details, the affected series entry is missing completely. In this Scenario, Uploading videos vie Opencast block proceeds successfully, but the uploaded video is finally not listed on the overview page (not assigned to the series correctly on Opencast).

We tested it out: As soon as you remove for example the second series from the Moodle Opencast block (in case 2 series IDs are set), the upload to Opencast works fine again. The series are set correctly and everything works as expected.

**Comment by TamaraGunkel** [comment]
I'm not sure if I understood the problem correctly. I can connect two series with one course and upload videos to both of them without problems. The videos are also listed everywhere.
Could you provide screenshots? That would help me to reproduce this.

**Comment by Tscheckoff** [comment]
Lets clear it up a little bit (I also made a few screenshots):

One series set = no issues. Two series set = no issues IF you upload the video to the 2nd connected series. But the issue is there if you try to use the 1st / main series (while still both series are connected to this one course). Reg. the screenshots: I uploaded three "WebEx Test" videos. Test Nr.1 is only one series connected = everything works, Test Nr.2 upload is two series connected (but 2nd series chosen as you can see in the list) = works and Test Nr.3 is with two series still connected to the course BUT the 1st [123456] series is chosen for the upload = doesn´t work. The series entry is missing in the event details and the video gets "randomly" published in another series altough its listed in the overview as part of [123456].

Overview of all three:
![OCast-Problem_Screenshot-8_all-three-uploads_no-markings](https://user-images.githubusercontent.com/99137358/155699846-e5460591-97e7-4ac9-8450-e047a6535754.JPG)

1st Upload / Test worked (series set in event details):
![OCast-Problem_Screenshot-1_only-one-series](https://user-images.githubusercontent.com/99137358/155700159-f34cad9a-1168-47f3-bb0c-c7f1e31fb396.JPG)

2nd Upload / Test worked (series set in event details):
![OCast-Problem_Screenshot-7_two-series-set_used-2nd-series-to-upload](https://user-images.githubusercontent.com/99137358/155699925-3f28f812-2ed6-48ab-b080-3c41302bf0dd.JPG)

3rd Upload / Test did not work (series is missing in event details / published to random series):
![OCast-Problem_Screenshot-6_OC-Details-for-3rd-test](https://user-images.githubusercontent.com/99137358/155700044-3a025678-6035-4079-aa7e-a16a790bd7da.JPG)

**Comment by TamaraGunkel** [comment]
Hey,
thanks for the additional information. 
I was able to reproduce this. I fixed it and will release it with the next version.

**Comment by Tscheckoff** [comment]
Thats great to hear. Thank you for your time / for the fix!
