### ISSUE TITLE
missing German translations 

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-block_opencast#278]
I am not sure if there are more missing translations, but here is an example:

![image1](https://user-images.githubusercontent.com/204101/164417742-bed52408-3758-4213-b3b5-a40509095e9d.jpeg)

**Comment by mwuttke** [comment]
Hello taraghi,

Basically, the language strings of the Moodle plugins are maintained in the following database: [https://lang.moodle.org/](https://lang.moodle.org/) Feel free to register on this site and pick the appropriate plugin and translate the missing language strings and then submit them as suggestions. The person responsible - in this case Ralf Krause - for the German language package will then review your suggestions in order to approve, modify or reject them. If your suggestions are accepted, then as far as I know they should also be available within 24 hours for the currently supported Moodle versions.

I hope that I could help you a little further. ;-)

Thanks & Greetings,
Michael

BTW: I have translated the language strings from your screen shot in the meantime.

**Comment by taraghi** [comment]
Thank you very much

**Comment by ferishili** [comment]
Hi, thanks for the report and answer.
I assume that this is no longer an issue, therefore I am going to close it.
