### ISSUE TITLE
"Invalid course module ID" When trying to create Episode/Series LTI

### ISSUE THREAD

**Issue by Lyx52** [Opencast-Moodle/moodle-block_opencast#344]
I have a problem where I create series video LTI but the activity is not created and when I try to access it via video overview page it redirects to the tool but it displays "Invalid course module ID" 
![image](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/55701905/bbc52251-cced-4acc-8695-ac3843c4f0af)

I have created Opencast series LTI in moodle:
![image](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/55701905/394cc686-8954-467f-895b-3cd278b39bc5)

Configured Opencast LTI settings:
![image](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/55701905/4d14f2bb-ac09-4b32-8a35-5e6228df5769)

And my LTI connection is working:
![image](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/55701905/a158e035-90f8-4b26-862b-e700fb2c3e6b)

**Comment by ferishili** [comment]
@Lyx52, thank you for sharing your issue here. We appreciate your engagement. However, our issue repository is primarily reserved for addressing bugs and feature requests. To better assist with questions and discussions like the one you've raised, we encourage you to join our mailing list [lms@opencast.org](https://groups.google.com/a/opencast.org/g/lms) or, even better, become a part of the matrix channel [Opencast-Moodle Usergroup](https://matrix.to/#/#opencast-moodle-usergroup:matrix.org).

Regarding the problem you're encountering—misconfiguring the LTI external tool—the solution lies in:
1. `Tool URL`: must be your opencast intance url ending with `/lti `something like: `https://{your.oc.instance.hostname}/lti`
2. `Custom parameters`: (for **SERIES**) this must be set to: `tool=ltitools/series/index.html` in one line without any double-quotes

If you have any further questions or need assistance, please don't hesitate to ask using the communication channels mentioned above. We're here to help.

**Comment by ferishili** [comment]
Therefore, I close this issue.
