### ISSUE TITLE
Suggestion: Add multi- / bulk upload feature

### ISSUE THREAD

**Issue by brantned** [Opencast-Moodle/moodle-block_opencast#350]
We have lecturers which upload quite often a bulk of videos. (Sometimes even 20 up to 40 pcs at once.)

Single uploads are therefor quite a pain / take away alot of time. (As you have to wait for the single video to upload.
And only after it finished you can continue again to edit the metadata of the next one + upload again.)

<ins>Great would be therefor:</ins>

- Bulk upload for at least a few videos at once (maybe a limited amount if needed for whatever reason)
- Upload with the names of the files as titles (or editing of at least the titles of the events per video entry)
- MAYBE keep the system as it is but add a queue feature which you can trigger then at once so its getting processed one after each other

Would be great to have a bulk upload option of any kind.
Btw.: Thx for your hard work and greetings from Austria.

**Comment by NinaHerrmann** [comment]
Hey @brantned,
I definitely agree - some of the metadata is also repetitive. I think we did not focus on this since for big uploads (at least in our case), we need the chunk_upload to bypass the server upload limits. I am unsure about the design decisions of chunk upload - therefore @justusdieckmann might have time to comment on the feasibility of the feature and the expected workload. 
Thanks for reporting!

**Comment by ypatios** [comment]
We're also interested in this feature which is a requirement for a current project of ours. Any news would be appreciated :)

**Comment by NinaHerrmann** [comment]
We are still stuck in the pipeline reviewing recent pull requests on deleting the block. Therefore, we will not make any estimation when we will have a closer look. If we have time to work on it, we will let you know. However, please keep in mind that anyone can implement it, this is the idea of OpenSource Software!
