### ISSUE TITLE
Subtitles are not available in the Moodle Block Plugin under Manage Transcriptions

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#368]
If you as a teacher want to handle with existing subtitles in the block plugin for Opencast from Moodle, this unfortunately does not work as expected. The VTT file is available as a direct download. However, it is not available for download under "Action" -> "Manage Transcriptions".

Is it possible that the block plugin cannot yet handle the conversion of subtitles from attachments to tracks?

Our setup:
OS: Debian bookworm
Moodle version: 4.1.9+
Opencast version: 15.3
Moodle block plugin for Opencast Version: v4.3-r2

**Comment by NinaHerrmann** [comment]
Hey Michael, thank you for reporting the issue. Although this is already a very good description, I was wondering if I understood it correctly, that this "feature" has not been implemented yet. 
( I agree that it would be logical that it works, just wondering if it was working previously...)
Then I would label it as a feature/bug depending on your answer :)

**Comment by mwuttke** [comment]
@NinaHerrmann, sorry it was my fault. I didn't mean editing but the functions under _Manage Transcriptions_ that Farbod has implemented and that used to work in older versions of the plugin/Opencast version: upload, download, overwrite or delete of a vtt file.

**Comment by ferishili** [comment]
According to Michael, the only thing that has problem right now is the download of subtitles under `"Action" -> "Manage Transcriptions"`

**Comment by ferishili** [comment]
The outcome of our debugging session:
- **(Opencast side)** The subtitles generated by `Amberscript` or `Whisper` workflows, do not show up in the Transcription Management, the reason is the missing configuration parts in those workflows to provide the generated caption as media (assets) in opencast.
- **(Opencast side)** The Manually upload transcriptions via Transcription Management or parallel with video upload do not show up in the direct download list, the reason is again the missing configuration part in the `republish-and-caption` workflow in opencast to have it as publication.
- **(Plugin side)** If you manually upload the same transcription (with same flavor) via Transcription Management in order to overwrite, you will end up with a new one instead of a replacement, which has to be taken care of in the plugin!
Hope the point were clear!
