### ISSUE TITLE
Standard series deleted - Error with new standard

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-block_opencast#374]
Hi,

I inadvertently created two series. I just deleted the first series, which was set as the "default". But now I can't set the second series as the default:

![image1](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/204101/8fe98982-bc80-4442-945c-d0a927cb372f)
![image2](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/204101/cd270ee0-1fbf-4d4b-a67b-465792fda094)
![image3](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/204101/1fc15601-812c-4338-8b83-98d318fb95ed)

**Comment by ferishili** [comment]
The following issues are linked to this issue and will be included into the fix for this problem:
- https://github.com/Opencast-Moodle/moodle-block_opencast/issues/232 => the isdefault = 1 must become unique for each course, meaning there should be only 1 default series for a course at all times.
- https://github.com/Opencast-Moodle/moodle-block_opencast/issues/263 => the default series in a course should not be deleted, unless the default is set to other series and then you could delete a serie!
