### ISSUE TITLE
Video URLs in overview page

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#58]
Hello,
we are wondering if you could add a column to the list of released videos at `blocks/opencast/index.php` that contains the URL to each video.
The reason we would like to have such a feature is that we don't trust our users to find the video they want to embed (in the Atto editor) via "Media", "Browse repositories..." and "Opencast".

Is this something you would consider?

If not, would you instead consider refactoring the way this table is generated in `index.php`: https://github.com/unirz-tu-ilmenau/moodle-block_opencast/blob/f5328cd42241ccf68f324873bf9c154ac9a2af84/index.php#L157-L194 so that the table is created by a method of the renderer and/or a template? This way we would be able to override the renderer or template in our theme and add the desired column this way.

**Comment by tobiasreischmann** [comment]
I already did some tests to display the block also to students and show all published videos as links. However, this is not that easy, since the user is not yet authenticated at the opencast system. Thus we need to embed a similar system than the authentication of https://github.com/learnweb/moodle-filter_opencastfilter.
It is definitely something for future development.

**Comment by do-you-even-curl** [comment]
Ok. Glad to hear this has already been thought of.
I get what you mean with the authentication problem. One possibility I can think of would be to have a separate page (i.e. PHP file) which takes the Opencast video ID as an input parameter and just contains a self-submitting LTI form like in the filter plugin (or just redirects to the Opencast video page if the `JSESSIONID` cookie is already set). Then we could display links to this page in the list of published videos instead of showing direct links to Opencast pages. When following such a link you would have to either login/be logged in to Moodle or be already authenticated in Opencast to view the video. They could also be embedded as iframes.
The filter could make sure any direct links to Opencast video pages embedded anywhere are replaces by links to this new page (in case a teacher follows such a link and after being forwarded to the Opencast page just copies _its_ URL and embeds it somewhere in Moodle).

**Comment by TamaraGunkel** [comment]
Hey,
since this issue is already older, is it still relevant?

**Comment by ferishili** [comment]
Hi @TamaraGunkel 
would you please assign this issue to me?
Thanks in advance.

**Comment by ferishili** [comment]
Hi @t-schroeder,
Please try the new PR #298 out and check if it could solve/satisfy this issue/request.
Thanks in advance.
