### ISSUE TITLE
Feature request: Why not make the video clickable to watch?

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#96]
If so, it will be very intuitive for students to watch lecture videos and for teachers to upload videos  and mapping series.

**Comment by tobiasreischmann** [comment]
Which video are you referring to? Actually, it is not that easy to implement it. We are currently thinking about what is the best process for teachers to upload and include videos and were these videos should be displayed to the user. But that takes a lot of work.

**Comment by fishfree** [comment]
@tobiasreischmann I mean the videos displayed in the block_opencast block. I see.  Thank you for your great work!

**Comment by TamaraGunkel** [comment]
Hi,
I'm currently looking through all the old issues.
We have implemented an activity that allows teachers to provide the videos so that students can directly watch them in Moodle (we'll release it in the following days): https://github.com/Opencast-Moodle/moodle-mod_opencast

There is also an integration with the block that allows teachers to easily add activities from the block.
We'll further develop the activity but have currently no intention of adding a similar functionality to the block. 
Thus I'll close this issue.
If you still miss this functionality, feel free to reopen the issue and create a pull request :)
