### ISSUE TITLE
Feature: Delete series when course is deleted

### ISSUE THREAD

**Issue by mtneug** [Opencast-Moodle/moodle-block_opencast#99]
*This idea was raised at Opencast DACH 2019*

This should probably be configurable, maybe even per course.

**Comment by abias** [comment]
Some thoughts about this issue:
* It would be a no-brainer to add an event listener for the course_deleted event to the block_opencast plugin and, within the event handler, delete the Opencast series of the Moodle course including all videos over the Opencast API. This would then be fully-automated but also not really controllable. 
* Things get more complicated and the deletion must not not be fully-automated if a) the videos from within the Opencast series are used on other sinks besides the Moodle course as well or b) there is a policy that Opencast videos should be preserved in some kind of university media archive or c) some sort of multiple series support is implemented in #169.
* There is the excellent Course Life Cycle plugin for Moodle on https://moodle.org/plugins/tool_lifecycle and it would be worthwhile to create a subplugin for course life cycle which handles Opencast videos from within a Moodle course during the course deletion process more sophisticatedly.

**Comment by moodle-mw** [comment]
+1

**Comment by ferishili** [comment]
This feature request came down to the lifecycle_opencast step and has its own repository now under [Opencast-Moodle/moodle-lifecyclestep_opencast](https://github.com/Opencast-Moodle/moodle-lifecyclestep_opencast)

Comments/Ideas/Issues etc. must be continued under above-mentioned repository. With that said, this issue did its job and it is completed.

**Comment by NinaHerrmann** [comment]
I am sorry to enter the discussed when it was already ended - however, I have some open questions... 

> It would be a no-brainer to add an event listener for the course_deleted event to the block_opencast plugin and, within the event handler, delete the Opencast series of the Moodle course including all videos over the Opencast API. This would then be fully-automated but also not really controllable.

Actually there are even functions like block_xxyyzz_pre_course_delete which should do the job without an event Listener.

> Things get more complicated and the deletion must not not be fully-automated if a) the videos from within the Opencast series are used on other sinks besides the Moodle course as well or b) there is a policy that Opencast videos should be preserved in some kind of university media archive or c) some sort of multiple series support is implemented in
> https://github.com/Opencast-Moodle/moodle-block_opencast/issues/169.

I see that whenever deleting a course it has to be checked if the video is used in any other context - however the same problem arises when deleting a course with the lifecycle plugin. Correct me if I am wrong but from my point of view the same mechanism would be available when using the pre build functions.

> There is the excellent Course Life Cycle plugin for Moodle on https://moodle.org/plugins/tool_lifecycle and it would be worthwhile to create a subplugin for course life cycle which handles Opencast videos from within a Moodle course during the course deletion process more sophisticatedly.

I really appreciate the recommendation but from my point of view tool lifecycle is not the way to handle proper deletion of videos. 
A) What happens when courses are deleted in other ways? The plugin should be capable to handle it!
B) Readability of workflows: imagine every activity would have a lifecycle step...

I can understand that you already put work in the lifecycle step but I would not recommend to handle it that way - but to copy the functionality to the suitable functions.

Please feel engaged to open the discussion again, if you disagree!
